routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Auth::routes(['verify' => true]);
Auth::routes();
Route::get('email/verify', 'Auth\VerificationController@show')->name('verification.notice');
Route::get('email/verify/{id}', 'Auth\VerificationController@verifyUser')->name('verification.verify');
Route::get('email/resend', 'Auth\VerificationController@resend')->name('verification.resend');

Route::group(['as' => 'message.'], function () {
    Route::get('/', 'MessageController@index')->name('index');
    Route::post('/', 'MessageController@store')->name('store');
    
    Route::prefix('message')->group(function () {
        Route::post('edit', 'MessageController@edit')->name('edit');
        Route::post('delete', 'MessageController@delete')->name('delete');
        Route::put('{id}', 'MessageController@update')->name('update');
        Route::delete('{id}', 'MessageController@destroy')->name('confirm.delete');
    });
});

// Route List for Admin
Route::group([
    'prefix'     => 'admin',
    'namespace'  => 'Admin',
    'middleware' => 'admin'
], function () {
    Route::get('/', function () {
        return redirect()->route('dashboard.index');
    });

    Route::group(['prefix'=> 'dashboard', 'as' => 'dashboard.'], function () {
        Route::get('/', 'DashboardController@index')->name('index');
    
        Route::group(['prefix'=> 'message', 'as' => 'message.'], function () {
            Route::post('multi-delete', 'DashboardController@multiDelete')->name('multi-delete');
            Route::post('{id}/recover', 'DashboardController@recover')->name('recover');
            Route::delete('{id}', 'DashboardController@delete')->name('delete');
            Route::delete('{id}/image', 'DashboardController@deleteImage')->name('image.delete');
        });
    });
});

app/Models/Message.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Hash;
use App\Traits\HandleUploadedImage;

class Message extends Model
{
    use HandleUploadedImage, SoftDeletes;

    protected static $imagePath = 'images/messages';

    protected $fillable = [
        'name', 'title', 'body', 'password', 'image'
    ];

    public static function boot()
    {
        parent::boot();

        static::updated(function ($message) {
            if ($message->wasChanged('image')) {
                self::removeImage($message->getOriginal('image'));
            }
        });

        static::deleted(function ($message) {
            self::removeImage($message->image);
        });
    }

    public function user()
    {
        return $this->belongsTo('App\Models\User');
    }

    public function setPasswordAttribute($value)
    {
        if ($value !== null && $value !== '') {
            $this->attributes['password'] = Hash::make($value);
        }
    }

    public function setImageAttribute($image)
    {
        $this->attributes['image'] = ltrim($image, self::$imagePath . '/');
    }

    public function getFullImageAttribute()
    {
        return 'storage/' . self::getImagePath() . '/' . $this->image;
    }

    public function getThumbnailImageAttribute()
    {
        return 'storage/' . self::getThumbnailPath() . '/' . $this->image;
    }
}

resources/views/admin/index.blade.php
@extends('layouts.dashboard')

@section('title', 'Dashboard')

@section('css')
    
@endsection

@section('content')
  <section class="content">
    <div class="row">
      <div class="col-xs-12"><!-- /.col-xs-12 -->
        <div class="box box-success">
          <div class="box-header with-border">
            <h1 class="font-18 m-0">Timedoor Challenge - Level 9</h1>
          </div>
          <div class="box-body">
            
            @include('admin.search-form')

            @include('admin.search-result')
            
            <div class="text-center">
              <nav>
                {{ $messages->links() }}
              </nav>
            </div>
          </div>
        </div>
      </div><!-- /.col-xs-12 -->
    </div>
  </section>

  @if (session('notif'))
  <div class="alert alert-notif fade notification" tabindex="-1" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
      <strong>Info:</strong> The item was <strong>{{ session('notif') }}</strong> successfully
  </div>
  @endif

  <div class="modal fade" id="deleteMessageModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <div class="text-center">
            <h4 class="modal-title" id="myModalLabel">Delete Message</h4>
          </div>
        </div>
        <div class="modal-body pad-20">
          <p>Are you sure want to delete this message?</p>
        </div>
        <div class="modal-footer">
          <form id="deleteMessageForm" action="" method="post">
            @csrf
            @method('DELETE')
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-danger">Delete</button>
          </form>
        </div>
      </div>
    </div>
  </div>

  <div class="modal fade" id="deleteImageModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <div class="text-center">
            <h4 class="modal-title" id="myModalLabel">Delete Image</h4>
          </div>
        </div>
        <div class="modal-body pad-20">
          <p>Are you sure want to delete this Image?</p>
        </div>
        <div class="modal-footer">
          <form id="deleteImageForm" action="" method="post">
            @csrf
            @method('DELETE')
            <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
            <button type="submit" class="btn btn-danger">Delete</button>
          </form>
        </div>
      </div>
    </div>
  </div>

  <div class="modal fade" id="deleteSelectedModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
    <div class="modal-dialog">
      <div class="modal-content">
        <div class="modal-header">
          <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
          <div class="text-center">
            <h4 class="modal-title" id="myModalLabel">Delete Messages</h4>
          </div>
        </div>
        <div class="modal-body pad-20">
          <p>Are you sure want to delete this Messages?</p>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button type="submit" form="formResult" formaction="{{ route('dashboard.message.multi-delete') }}" class="btn btn-danger">Delete</button>
        </div>
      </div>
    </div>
  </div>
@endsection

@section('script')
  <script type="text/javascript">
    $('#selectAll').click(function () {
      $('input:checkbox').not(this).prop('checked', this.checked);     
      $('#deleteAll').prop('disabled', !this.checked);
    });

    $('input:checkbox').not('#selectAll').change(function () {
      var numOfChecked  = $('input:checkbox:checked').not('#selectAll').length;
      var numOfCheckbox = $('input:checkbox').not('#selectAll').length;

      if (numOfChecked > 0) {  
        $('#deleteAll').prop('disabled', false);
      } else {
        $('#deleteAll').prop('disabled', true);
      }

      if (numOfChecked === numOfCheckbox) {
        $('#selectAll').prop('checked', true);
      } else {
        $('#selectAll').prop('checked', false);
      }
    });

    $('#deleteMessageModal').on('show.bs.modal', function (e) {
      var id  = $(e.relatedTarget).data('id');
      var url = "{{ route('dashboard.message.delete', ['id' => '']) . '/' }}" + id;
      
      $('#deleteMessageForm').prop('action', url);
    });

    $('#deleteImageModal').on('show.bs.modal', function (e) {
      var id  = $(e.relatedTarget).data('id');
      var url = "{{ route('dashboard.message.image.delete', ['id' => 'id']) }}";
      var url = url.replace('/id/', '/' + id + '/');
      
      $('#deleteImageForm').prop('action', url);
    });

    @if (session('notif'))
      $(document).ready(function () {
        var notification = $(".notification");

        notification.delay(500).fadeTo("slow", 1);

        notification.delay(3000).fadeTo("slow", 0, function () {
          notification.alert('close');
        });
      });
    @endif

  </script>
@endsection

resources/views/admin/login.blade.php
<html>
  <head>
    <title>Timedoor Challenge - Level 8 | Login</title>
    
    <?php include('template/style.php') ?>
    <?php include('template/script.php') ?>
    
    <!-- Javascript -->
    <script type="text/javascript" src="js/jquery.js"></script>
    <script type="text/javascript" src="js/bootstrap.min.js"></script>
    <!-- Javascript End -->
  </head>
  
  <body id="login">
    <div class="login-box">
      <div class="login-box-head">
        <h1>Login</h1>
        <p>Please login to continue...</p>
      </div>
      <div class="login-box-body">
        <div class="form-group">
          <input type="text" class="form-control" placeholder="Username">
          <p class="mt-5 small text-danger">*this field can't be empty</p>
        </div>
        <div class="form-group">
          <input type="password" class="form-control" placeholder="Password">
          <p class="mt-5 small text-danger">*this field can't be empty</p>
        </div>
      </div>
      <div class="login-box-footer">
        <div class="text-right">
          <a href="index.php" class="btn btn-primary">Submit</a>
        </div>
      </div>
    </div>
  </body>
  
</html>

resources/views/admin/search-form.blade.php
<div class="bordered-box mb-20">
  <form class="form" role="form">
    <table class="table table-no-border mb-0">
      <tbody>
        <tr>
          <td width="80"><b>Title</b></td>
          <td>
            <div class="form-group mb-0">
              <input type="text" class="form-control" name="title" value="{{ request('title') }}">
            </div>
          </td>
        </tr>
        <tr>
          <td><b>Body</b></td>
          <td>
            <div class="form-group mb-0">
              <input type="text" class="form-control" name="body" value="{{ request('body') }}">
            </div>
          </td>
        </tr>
      </tbody>
    </table>
    <table class="table table-search">
      <tbody>
        <tr>
          <td width="80"><b>Image</b></td>
          <td width="60">
            <label class="radio-inline">
              @if (request('image_filter') === 'with')
                <input type="radio" name="image_filter" value="with" checked> with
              @else
                <input type="radio" name="image_filter" value="with"> with
              @endif
            </label>
          </td>
          <td width="80">
            <label class="radio-inline">
              @if (request('image_filter') === 'without')
                <input type="radio" name="image_filter" value="without" checked> without
              @else
                <input type="radio" name="image_filter" value="without"> without
              @endif
            </label>
          </td>
          <td>
            <label class="radio-inline">
              @if (request('image_filter') === 'unspecified' || empty(request('image_filter')))
                <input type="radio" name="image_filter" value="unspecified" checked> unspecified
              @else
                <input type="radio" name="image_filter" value="unspecified"> unspecified
              @endif
            </label>
          </td>
        </tr>
        <tr>
          <td width="80"><b>Status</b></td>
          <td>
            <label class="radio-inline">
              @if (request('status') === 'on')
                <input type="radio" name="status" value="on" checked> on
              @else
                <input type="radio" name="status" value="on"> on
              @endif
            </label>
          </td>
          <td>
            <label class="radio-inline">
              @if (request('status') === 'delete')
                <input type="radio" name="status" value="delete" checked> delete
              @else
                <input type="radio" name="status" value="delete"> delete
              @endif
            </label>
          </td>
          <td>
            <label class="radio-inline">
              @if (request('status') === 'unspecified' || empty(request('status')))
                <input type="radio" name="status"  value="unspecified" checked> unspecified
              @else
                <input type="radio" name="status"  value="unspecified"> unspecified
              @endif
            </label>
          </td>
        </tr>
        <tr>
          <td>
            <button type="submit" class="btn btn-default mt-10">
              <i class="fa fa-search"></i> Search
            </button>
          </td>
        </tr>
      </tbody>
    </table>
  </form>
</div>

resources/views/admin/search-result.blade.php
<form method="post" id="formResult">
  @csrf
  <table class="table table-bordered">
    <thead>
      <tr>
        <th><input type="checkbox" id="selectAll"></th>
        <th>ID</th>
        <th>Title</th>
        <th>Body</th>
        <th width="200">Image</th>
        <th>Date</th>
        <th width="50">Action</th>
      </tr>
    </thead>
    <tbody>
      @foreach ($messages as $message)
        @if ($message->trashed())
        <tr class="bg-gray-light">
          <td>&nbsp;</td>
        @else
        <tr>
          <td><input type="checkbox" name="id[]" value="{{ $message->id }}"></td>
        @endif
          
          <td>{{ $message->id }}</td>
          <td>{{ $message->title }}</td>
          <td>{!! nl2br(e($message->body)) !!}</td>
          
          @if ($message->image && !$message->trashed())
            <td>
              <img class="img-prev" src="{{ asset($message->thumbnail_image) }}">
              <button type="button" data-toggle="modal" data-target="#deleteImageModal" data-id="{{ $message->id }}" class="btn btn-danger ml-10 btn-img" rel="tooltip" title="Delete Image">
                <i class="fa fa-trash"></i>
              </button>
            </td>
          @else
            <td>-</td>
          @endif

          <td>
            {{ $message->created_at->format('d-m-Y') }}<br/>
            <span class="small">{{ $message->created_at->format('H:i:s') }}</span>
          </td>
          @if ($message->trashed())
            <td>
              <button type="submit" formaction="{{ route('dashboard.message.recover', ['id' => $message->id]) }}" class="btn btn-default" rel="tooltip" title="Recover"><i class="fa fa-repeat"></i></button>
            </td>
          @else
            <td>
              <button type="button" data-toggle="modal" data-target="#deleteMessageModal" data-id="{{ $message->id }}" class="btn btn-danger" rel="tooltip" title="Delete">
                <i class="fa fa-trash"></i>
              </button>
            </td>
          @endif
        </tr>
      @endforeach
    </tbody>
  </table>
</form>

<button type="button" id="deleteAll" class="btn btn-default mt-5" data-toggle="modal" data-target="#deleteSelectedModal" disabled>Delete Checked Items</button>