routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Auth::routes(['verify' => true]);
Auth::routes();
Route::get('email/verify', 'Auth\VerificationController@show')->name('verification.notice');
Route::get('email/verify/{id}', 'Auth\VerificationController@verifyUser')->name('verification.verify');
Route::get('email/resend', 'Auth\VerificationController@resend')->name('verification.resend');

Route::group(['as' => 'message.'], function () {
    Route::get('/', 'MessageController@index')->name('index');
    Route::post('/', 'MessageController@store')->name('store');
    
    Route::prefix('message')->group(function () {
        Route::post('edit', 'MessageController@edit')->name('edit');
        Route::post('delete', 'MessageController@delete')->name('delete');
        Route::put('{id}', 'MessageController@update')->name('update');
        Route::delete('{id}', 'MessageController@destroy')->name('confirm.delete');
    });
});

// Route List for Admin
Route::group([
    'prefix'     => 'admin',
    'namespace'  => 'Admin',
    'middleware' => 'admin'
], function () {
    Route::get('/', function () {
        return redirect()->route('dashboard.index');
    });

    Route::group(['prefix'=> 'dashboard', 'as' => 'dashboard.'], function () {
        Route::get('/', 'DashboardController@index')->name('index');
    
        Route::group(['prefix'=> 'message', 'as' => 'message.'], function () {
            Route::post('multi-delete', 'DashboardController@multiDelete')->name('multi-delete');
            Route::post('{id}/recover', 'DashboardController@recover')->name('recover');
            Route::delete('{id}', 'DashboardController@delete')->name('delete');
            Route::delete('{id}/image', 'DashboardController@deleteImage')->name('image.delete');
        });
    });
});

resources/views/template/footer.blade.php
<p class="font12">Copyright &copy; <script>document.write(new Date().getFullYear());</script> by <a href="https://timedoor.net" class="text-green">PT. TIMEDOOR INDONESIA</a> </p>

resources/views/template/header.blade.php
<nav class="navbar navbar-default" role="navigation">
  <div class="container">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a href="{{ route('message.index') }}">
        <h2 class="font16 text-green mt-15"><b>Timedoor 30 Challenge Programmer</b></h2>
      </a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav navbar-right">
        @guest
          <li><a href="{{ route('login') }}">Login</a></li>
          <li><a href="{{ route('register') }}">Register</a></li>
        @else
          <li>
            <a href="{{ route('logout') }}" 
               onclick="event.preventDefault();
                        document.getElementById('logout-form').submit();">
              Logout
            </a>

            <form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
              @csrf
            </form>
          </li>
        @endguest
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

resources/views/template/script.blade.php
<!-- Javascript -->
<script type="text/javascript" src="/js/jquery.js"></script>
<script type="text/javascript" src="/js/bootstrap.min.js"></script>
<!-- Javascript End -->

resources/views/template/style.blade.php
<!-- CSS -->
<link rel="stylesheet" type="text/css" href="/css/bootstrap.min.css">
<link rel="stylesheet" type="text/css" href="/css/font-awesome.min.css">
<link rel="stylesheet" type="text/css" href="/css/style.css">
<link rel="stylesheet" type="text/css" href="/css/tmdrPreset.css">
<!-- CSS End -->