routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Auth::routes(['verify' => true]);
Auth::routes();
Route::get('email/verify', 'Auth\VerificationController@show')->name('verification.notice');
Route::get('email/verify/{id}', 'Auth\VerificationController@verifyUser')->name('verification.verify');
Route::get('email/resend', 'Auth\VerificationController@resend')->name('verification.resend');

Route::group(['as' => 'message.'], function () {
    Route::get('/', 'MessageController@index')->name('index');
    Route::post('/', 'MessageController@store')->name('store');
    
    Route::prefix('message')->group(function () {
        Route::post('edit', 'MessageController@edit')->name('edit');
        Route::post('delete', 'MessageController@delete')->name('delete');
        Route::put('{id}', 'MessageController@update')->name('update');
        Route::delete('{id}', 'MessageController@destroy')->name('confirm.delete');
    });
});

// Route List for Admin
Route::group([
    'prefix'     => 'admin',
    'namespace'  => 'Admin',
    'middleware' => 'admin'
], function () {
    Route::get('/', function () {
        return redirect()->route('dashboard.index');
    });

    Route::group(['prefix'=> 'dashboard', 'as' => 'dashboard.'], function () {
        Route::get('/', 'DashboardController@index')->name('index');
    
        Route::group(['prefix'=> 'message', 'as' => 'message.'], function () {
            Route::post('multi-delete', 'DashboardController@multiDelete')->name('multi-delete');
            Route::post('{id}/recover', 'DashboardController@recover')->name('recover');
            Route::delete('{id}', 'DashboardController@delete')->name('delete');
            Route::delete('{id}/image', 'DashboardController@deleteImage')->name('image.delete');
        });
    });
});

app/Models/Message.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Hash;
use App\Traits\HandleUploadedImage;

class Message extends Model
{
    use HandleUploadedImage, SoftDeletes;

    protected static $imagePath = 'images/messages';

    protected $fillable = [
        'name', 'title', 'body', 'password', 'image'
    ];

    public static function boot()
    {
        parent::boot();

        static::updated(function ($message) {
            if ($message->wasChanged('image')) {
                self::removeImage($message->getOriginal('image'));
            }
        });

        static::deleted(function ($message) {
            self::removeImage($message->image);
        });
    }

    public function user()
    {
        return $this->belongsTo('App\Models\User');
    }

    public function setPasswordAttribute($value)
    {
        if ($value !== null && $value !== '') {
            $this->attributes['password'] = Hash::make($value);
        }
    }

    public function setImageAttribute($image)
    {
        $this->attributes['image'] = ltrim($image, self::$imagePath . '/');
    }

    public function getFullImageAttribute()
    {
        return 'storage/' . self::getImagePath() . '/' . $this->image;
    }

    public function getThumbnailImageAttribute()
    {
        return 'storage/' . self::getThumbnailPath() . '/' . $this->image;
    }
}

app/Http/Controllers/MessageController.php
<?php

namespace App\Http\Controllers;

use App\Models\Message;
use Illuminate\Http\Request;
use App\Http\Requests\MessageRequest;
use Illuminate\Support\Facades\Auth;
use Illuminate\Database\Eloquent\ModelNotFoundException;

class MessageController extends Controller
{
    public function __construct()
    {
        $this->middleware('check.verified');
    }

    public function index()
    {
        $messages = Message::latest()->paginate(10);

        if (session('id') || old('id')) {
            $msg = Message::find(session('id') ?? old('id'));
        }

        return view('message.index', [
            'messages' => $messages,
            'msg'      => $msg ?? ''
        ]);
    }

    public function store(MessageRequest $request)
    {
        $input = $request->validated();

        if ($request->hasFile('image')) {
            $input['image'] = Message::storeImage($request->image);
            Message::createThumbnail($request->image, 250);
        }

        if (Auth::check()) {
            Auth::user()->messages()->create($input);
        } else {
            Message::create($input);
        }

        return redirect('/');
    }

    public function delete(Request $request)
    {
        if (! $message = Message::find($request->id)) {
            return back()->with(['modal' => 'fail']);
        }

        try {
            $this->authorize('modify', [$message, $request->password]);
        } catch (\Exception $e) {
            return $this->redirectUnauthorizeModify($e->getMessage(), $request->id, 'delete');
        }
        
        return back()->with([
            'id'       => $request->id,
            'password' => $request->password,
            'modal'    => 'delete'
        ]);
    }
    
    public function destroy(Request $request)
    {
        if (! $message = Message::find($request->id)) {
            return back()->with(['modal' => 'fail']);
        }

        try {
            $this->authorize('modify', [$message, $request->password]);
        } catch (\Exception $e) {
            return $this->redirectUnauthorizeModify($e->getMessage(), $request->id, 'delete');
        }
        
        $message->forceDelete();
        
        return redirect('/');
    }
    
    public function edit(Request $request)
    {
        if (! $message = Message::find($request->id)) {
            return back()->with(['modal' => 'fail']);
        }

        try {
            $this->authorize('modify', [$message, $request->password]);
        } catch (\Exception $e) {
            return $this->redirectUnauthorizeModify($e->getMessage(), $request->id, 'edit');
        }
        
        return back()->with([
            'id'       => $request->id,
            'password' => $request->password,
            'modal'    => 'edit'
        ]);
    }
    
    public function update(MessageRequest $request)
    {
        if (! $message = Message::find($request->id)) {
            return back()->with(['modal' => 'fail']);
        }

        try {
            $this->authorize('modify', [$message, $request->confirm_password]);
        } catch (\Exception $e) {
            return $this->redirectUnauthorizeModify($e->getMessage(), $request->id, 'edit');
        }
        
        $input = $request->validated();
        
        if ($request->has('delete')) {
            $input['image'] = null;
        } elseif ($request->hasFile('image')) {
            $input['image'] = Message::storeImage($request->image);
            Message::createThumbnail($request->image, 250);
        }
        
        $message->update($input);

        return redirect('/');
    }

    protected function redirectUnauthorizeModify($message, $id, string $action)
    {
        if ($message === 'wrong') {
            return back()->with([
                'modal'  => 'wrong',
                'action' => $action,
                'id'     => $id
            ]);
        }

        return back()->with([
            'modal'   => 'fail',
            'message' => $message
        ]);
    }

}

resources/views/message/form-create.blade.php
<form action="" method="post" enctype="multipart/form-data">
  @csrf

  <div class="form-group">
    <label>Name</label>

    @if ($errors->hasBag('edit'))
      <input type="text" name="name" class="form-control" value="{{ auth()->user()->name ?? '' }}">
    @else
      <input type="text" name="name" class="form-control" value="{{ old('name') ?? auth()->user()->name ?? '' }}">
    @endif

    @if ($errors->has('name'))
      <p class="small text-danger mt-5">{{ $errors->first('name') }}</p>
    @endif
  </div>

  <div class="form-group">
    <label>Title</label>
    <input type="text" name="title" class="form-control" value="{{ $errors->hasBag('edit')? '': old('title') }}">
    @if ($errors->has('title'))
      <p class="small text-danger mt-5">{{ $errors->first('title') }}</p>
    @endif
  </div>

  <div class="form-group">
    <label>Body</label>
    <textarea rows="5" name="body" class="form-control">{{ $errors->hasBag('edit')? '': old('body') }}</textarea>
    @if ($errors->has('body'))
      <p class="small text-danger mt-5">{{ $errors->first('body') }}</p>
    @endif
  </div>

  <div class="form-group">
    <label>Choose image from your computer :</label>
    <div class="input-group">
      <input type="text" class="form-control upload-form" value="No file chosen" readonly>
      <span class="input-group-btn">
        <span class="btn btn-default btn-file">
          <i class="fa fa-folder-open"></i>&nbsp;Browse <input type="file" name="image" multiple>
        </span>
      </span>
    </div>
    @if ($errors->has('image'))
      <p class="small text-danger mt-5">{{ $errors->first('image') }}</p>
    @endif
  </div>

  @guest
    <div class="form-group">
      <label>Password</label>
      <input type="password" name="password" class="form-control">
      @if ($errors->has('password'))
        <p class="small text-danger mt-5">{{ $errors->first('password') }}</p>
      @endif
    </div>
  @endguest

  <div class="text-center mt-30 mb-30">
    <button type='submit' class="btn btn-primary">Submit</button>
  </div>
</form>

resources/views/message/index.blade.php
@extends('layouts.base')

@section('title', 'Timedoor Challenge - Level 9')

@section('css')
    
@endsection

@section('content')
  <div class="section">
    <div class="container">
      <div class="row">
        <div class="col-md-6 col-md-offset-3 bg-white p-30 box">
          <div class="text-center">
            <h1 class="text-green mb-30"><b>Level 9 Challenge</b></h1>
          </div>
          
          @include('message.form-create')

          <hr>
          @include('message.list')

          <div class="text-center mt-30">
            <nav>
              {{ $messages->links() }}
            </nav>
          </div>
        </div>
      </div>
    </div>
  </div>

  @if (session('modal') === 'delete')
    @include('message.modal.delete')
  @endif

  @if ($errors->hasBag('edit') || session('modal') === 'edit')
    @include('message.modal.edit')
  @endif

  @if (session('modal') === 'fail')
    @include('message.modal.fail')
  @endif

  @if (session('modal') === 'wrong')
    @include('message.modal.wrong')
  @endif
  
@endsection

@section('script')
    <script type="text/javascript" src="/js/custom.js"></script>

    <script type="text/javascript">
      @if (session('modal') === 'delete')
        $(document).ready(function () {
          $('#deleteModal').modal('show');
        });
      @endif

      @if ($errors->hasBag('edit') || session('modal') === 'edit')
        $(document).ready(function () {
          $('#editModal').modal('show');
        });
      @endif
      
      @if (session('modal') === 'fail')
        $(document).ready(function () {
          $('#failModal').modal('show');
        });
      @endif
        
      @if (session('modal') === 'wrong')
        $(document).ready(function () {
          $('#wrongModal').modal('show');
        });
      @endif
    </script>
@endsection

resources/views/message/list.blade.php
@foreach ($messages as $message)
  <div class="post">
    <div class="clearfix">
      <div class="pull-left">
        <h2 class="mb-5 text-green"><b>{{ $message->title }}</b></h2>
      </div>
      <div class="pull-right text-right">
        <p class="text-lgray">
          {{ $message->created_at->format('d-m-Y') }}<br/>
          <span class="small">{{ $message->created_at->format('H:i') }}</span>
        </p>
      </div>
    </div>

    <h4 class="mb-20">
      {{ $message->name ?? 'No Name' }} <span class="text-id">ID - {{ $message->user_id }}</span>
    </h4>

    <p>{!! nl2br(e($message->body)) !!}</p>
    
    <div class="img-box my-15">
      @if ($message->image)
        <img class="img-responsive center-block" src="{{ asset($message->thumbnail_image) }}" alt="image">
      @else
        <img class="img-responsive center-block" src="http://via.placeholder.com/1200x500" alt="image">
      @endif
    </div>
    
    @guest
      @if (! $message->user_id)
        <form class="form-inline mt-50" method="POST">
          @csrf
          <input type="hidden" name="id" value="{{ $message->id }}">
          <div class="form-group mx-sm-3 mb-2">
            <label class="sr-only">Password</label>
            <input type="password" name="password" class="form-control">
          </div>
          <button type="submit" formaction="{{ route('message.edit') }}" class="btn btn-default mb-2">
            <i class="fa fa-pencil p-3"></i>
          </button>
          <button type="submit" formaction="{{ route('message.delete') }}" class="btn btn-danger mb-2">
            <i class="fa fa-trash p-3"></i>
          </button>
        </form>
      @endif
    @else
      @if ($message->user_id && $message->user_id === auth()->user()->id)
        <form class="form-inline mt-50"  method="POST">
          @csrf
          <input type="hidden" name="id" value="{{ $message->id }}">
          <button type="submit" formaction="{{ route('message.edit') }}" class="btn btn-default mb-2">
            <i class="fa fa-pencil p-3"></i>
          </button>
          <button type="submit" formaction="{{ route('message.delete') }}" class="btn btn-danger mb-2">
            <i class="fa fa-trash p-3"></i>
          </button>
        </form>
      @endif
    @endguest
  </div>

@endforeach