routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Auth::routes(['verify' => true]);
Auth::routes();
Route::get('email/verify', 'Auth\VerificationController@show')->name('verification.notice');
Route::get('email/verify/{id}', 'Auth\VerificationController@verifyUser')->name('verification.verify');
Route::get('email/resend', 'Auth\VerificationController@resend')->name('verification.resend');

Route::group(['as' => 'message.'], function () {
    Route::get('/', 'MessageController@index')->name('index');
    Route::post('/', 'MessageController@store')->name('store');
    
    Route::prefix('message')->group(function () {
        Route::post('edit', 'MessageController@edit')->name('edit');
        Route::post('delete', 'MessageController@delete')->name('delete');
        Route::put('{id}', 'MessageController@update')->name('update');
        Route::delete('{id}', 'MessageController@destroy')->name('confirm.delete');
    });
});

// Route List for Admin
Route::group([
    'prefix'     => 'admin',
    'namespace'  => 'Admin',
    'middleware' => 'admin'
], function () {
    Route::get('/', function () {
        return redirect()->route('dashboard.index');
    });

    Route::group(['prefix'=> 'dashboard', 'as' => 'dashboard.'], function () {
        Route::get('/', 'DashboardController@index')->name('index');
    
        Route::group(['prefix'=> 'message', 'as' => 'message.'], function () {
            Route::post('multi-delete', 'DashboardController@multiDelete')->name('multi-delete');
            Route::post('{id}/recover', 'DashboardController@recover')->name('recover');
            Route::delete('{id}', 'DashboardController@delete')->name('delete');
            Route::delete('{id}/image', 'DashboardController@deleteImage')->name('image.delete');
        });
    });
});

app/Models/Message.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\SoftDeletes;
use Illuminate\Database\Eloquent\Model;
use Illuminate\Support\Facades\Hash;
use App\Traits\HandleUploadedImage;

class Message extends Model
{
    use HandleUploadedImage, SoftDeletes;

    protected static $imagePath = 'images/messages';

    protected $fillable = [
        'name', 'title', 'body', 'password', 'image'
    ];

    public static function boot()
    {
        parent::boot();

        static::updated(function ($message) {
            if ($message->wasChanged('image')) {
                self::removeImage($message->getOriginal('image'));
            }
        });

        static::deleted(function ($message) {
            self::removeImage($message->image);
        });
    }

    public function user()
    {
        return $this->belongsTo('App\Models\User');
    }

    public function setPasswordAttribute($value)
    {
        if ($value !== null && $value !== '') {
            $this->attributes['password'] = Hash::make($value);
        }
    }

    public function setImageAttribute($image)
    {
        $this->attributes['image'] = ltrim($image, self::$imagePath . '/');
    }

    public function getFullImageAttribute()
    {
        return 'storage/' . self::getImagePath() . '/' . $this->image;
    }

    public function getThumbnailImageAttribute()
    {
        return 'storage/' . self::getThumbnailPath() . '/' . $this->image;
    }
}

app/Http/Controllers/MessageController.php
<?php

namespace App\Http\Controllers;

use App\Models\Message;
use Illuminate\Http\Request;
use App\Http\Requests\MessageRequest;
use Illuminate\Support\Facades\Auth;
use Illuminate\Database\Eloquent\ModelNotFoundException;

class MessageController extends Controller
{
    public function __construct()
    {
        $this->middleware('check.verified');
    }

    public function index()
    {
        $messages = Message::latest()->paginate(10);

        if (session('id') || old('id')) {
            $msg = Message::find(session('id') ?? old('id'));
        }

        return view('message.index', [
            'messages' => $messages,
            'msg'      => $msg ?? ''
        ]);
    }

    public function store(MessageRequest $request)
    {
        $input = $request->validated();

        if ($request->hasFile('image')) {
            $input['image'] = Message::storeImage($request->image);
            Message::createThumbnail($request->image, 250);
        }

        if (Auth::check()) {
            Auth::user()->messages()->create($input);
        } else {
            Message::create($input);
        }

        return redirect('/');
    }

    public function delete(Request $request)
    {
        if (! $message = Message::find($request->id)) {
            return back()->with(['modal' => 'fail']);
        }

        try {
            $this->authorize('modify', [$message, $request->password]);
        } catch (\Exception $e) {
            return $this->redirectUnauthorizeModify($e->getMessage(), $request->id, 'delete');
        }
        
        return back()->with([
            'id'       => $request->id,
            'password' => $request->password,
            'modal'    => 'delete'
        ]);
    }
    
    public function destroy(Request $request)
    {
        if (! $message = Message::find($request->id)) {
            return back()->with(['modal' => 'fail']);
        }

        try {
            $this->authorize('modify', [$message, $request->password]);
        } catch (\Exception $e) {
            return $this->redirectUnauthorizeModify($e->getMessage(), $request->id, 'delete');
        }
        
        $message->forceDelete();
        
        return redirect('/');
    }
    
    public function edit(Request $request)
    {
        if (! $message = Message::find($request->id)) {
            return back()->with(['modal' => 'fail']);
        }

        try {
            $this->authorize('modify', [$message, $request->password]);
        } catch (\Exception $e) {
            return $this->redirectUnauthorizeModify($e->getMessage(), $request->id, 'edit');
        }
        
        return back()->with([
            'id'       => $request->id,
            'password' => $request->password,
            'modal'    => 'edit'
        ]);
    }
    
    public function update(MessageRequest $request)
    {
        if (! $message = Message::find($request->id)) {
            return back()->with(['modal' => 'fail']);
        }

        try {
            $this->authorize('modify', [$message, $request->confirm_password]);
        } catch (\Exception $e) {
            return $this->redirectUnauthorizeModify($e->getMessage(), $request->id, 'edit');
        }
        
        $input = $request->validated();
        
        if ($request->has('delete')) {
            $input['image'] = null;
        } elseif ($request->hasFile('image')) {
            $input['image'] = Message::storeImage($request->image);
            Message::createThumbnail($request->image, 250);
        }
        
        $message->update($input);

        return redirect('/');
    }

    protected function redirectUnauthorizeModify($message, $id, string $action)
    {
        if ($message === 'wrong') {
            return back()->with([
                'modal'  => 'wrong',
                'action' => $action,
                'id'     => $id
            ]);
        }

        return back()->with([
            'modal'   => 'fail',
            'message' => $message
        ]);
    }

}

resources/views/message/modal/delete.blade.php
<div class="modal fade" id="deleteModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Delete Data</h4>
      </div>
      <div class="modal-body pad-20">
        <p>Are you sure want to delete this item?</p>
      </div>
      <div class="modal-footer">
        <form method="POST" action="{{ route('message.confirm.delete', ['id' => session('id')]) }}">
          @csrf
          @method('DELETE')
          
          @guest
            <input type="hidden" name="password" value="{{ session('password') }}">
          @endguest

          <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
          <button type="submit" class="btn btn-danger" id="deleteBtn">Delete</button>
        </form>
      </div>
    </div>
  </div>
</div>

resources/views/message/modal/edit.blade.php
<div class="modal fade" id="editModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Edit Item</h4>
      </div>
      <form id="formUpdate" method="POST" action="{{ route('message.update', ['id' => $msg->id]) }}" enctype="multipart/form-data">
        @csrf
        @method('PUT')
        <input type="hidden" name="id" value="{{ $msg->id }}">

        @guest
          <input type="hidden" name="confirm_password" value="{{ old('confirm_password') ?? session('password') }}">
        @endguest

        <div class="modal-body">
          <div class="form-group">
            <label>Name</label>
            <input type="text" name="name" class="form-control" value="{{ old('name') ?? $msg->name }}">
            @if ($errors->edit->has('name'))
              <p class="small text-danger mt-5">{{ $errors->edit->first('name') }}</p>
            @endif
          </div>

          <div class="form-group">
            <label>Title</label>
            <input type="text" class="form-control" name="title" value="{{ old('title') ?? $msg->title }}">
            @if ($errors->edit->has('title'))
              <p class="small text-danger mt-5">{{ $errors->edit->first('title') }}</p>
            @endif
          </div>

          <div class="form-group">
            <label>Body</label>
            <textarea rows="5" name="body" class="form-control">{{ old('body') ?? $msg->body }}</textarea>
            @if ($errors->edit->has('body'))
              <p class="small text-danger mt-5">{{ $errors->edit->first('body') }}</p>
            @endif
          </div>
          <div class="form-group row">
            <div class="col-md-4">
              @if ($msg->image)
                <img class="img-responsive" src="{{ asset($msg->thumbnail_image) }}" alt="image">
              @else
                <img class="img-responsive" src="http://via.placeholder.com/1200x500" alt="image">
              @endif
            </div>
            <div class="col-md-8 pl-0">
              <label>Choose image from your computer :</label>
              <div class="input-group">
                <input type="text" class="form-control upload-form" value="No file chosen" readonly>
                <span class="input-group-btn">
                  <span class="btn btn-default btn-file">
                    <i class="fa fa-folder-open"></i>&nbsp;Browse <input type="file" name="image" multiple>
                  </span>
                </span>
              </div>
              @if ($errors->edit->has('image'))
                <p class="small text-danger mt-5">{{ $errors->edit->first('image') }}</p>
              @endif
              <div class="checkbox">
                <label>
                  <input type="checkbox" name="delete" value="delete">Delete image
                </label>
              </div>
            </div>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Close</button>
          <button type="submit" class="btn btn-primary" id="updateBtn" data-id="{{ $msg->id }}">Save changes</button>
        </div>
      </form>
    </div>
  </div>
</div>

resources/views/message/modal/fail.blade.php
<div class="modal fade" id="failModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">Ooppsss!!</h4>
      </div>
      <div class="modal-body pad-20">
        <p>{{ session('message') ?? 'Message not Found! Please select other message!' }}</p>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
      </div>
    </div>
  </div>
</div>

resources/views/message/modal/wrong.blade.php
<div class="modal fade" id="wrongModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        <h4 class="modal-title" id="myModalLabel">{{ ucfirst(session('action')) }} Data</h4>
      </div>
      <form id="form-wrong" method="POST" action="{{ route('message.' . session('action'), ['id' => $msg->id]) }}">
        @csrf
        <div class="modal-body pad-20">
          <div class="clearfix">
            <div class="pull-left">
              <h2 class="mb-5 text-green"><b>{{ $msg->title }}</b></h2>
            </div>
            <div class="pull-right text-right">
              <p class="text-lgray">
                {{ $msg->created_at->format('d-m-Y') }}<br/>
                <span class="small">{{ $msg->created_at->format('H:i') }}</span>
              </p>
            </div>
          </div>
            
            <h4 class="mb-20">
              {{ $msg->name ?? 'No Name' }} <span class="text-id">ID - {{ $msg->user_id }}</span>
            </h4>
            
            <p>{!! nl2br(e($msg->body)) !!}</p>
            
          <div class="img-box my-15">
            @if ($msg->image)
              <img class="img-responsive" style="max-height: 200px;" src="{{ asset($msg->thumbnail_image) }}" alt="image">
            @else
              <img class="img-responsive" style="max-height: 200px;" src="http://via.placeholder.com/1200x500" alt="image">
            @endif
          </div>

          <div class="form-group">
            <label>Password</label>
            <input type="password" name="password" class="form-control">
            <p class="small text-danger mt-5">Password doesn't match!!</p>
          </div>
        </div>
        <div class="modal-footer">
          <button type="button" class="btn btn-default" data-dismiss="modal">Cancel</button>
          <button id="confirmBtn" type="submit" class="btn btn-danger">{{ ucfirst(session("action")) }}</button>
        </div>
      </form>
    </div>
  </div>
</div>